name: Dev Pipeline

on:
  push:
    branches:
      - dev

permissions: write-all

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_API_KEY }}

      - name: Build Docker Image
        id: docker_build
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${IMAGE_TAG} .
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ env.IMAGE_TAG }}

  terraform_validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

