name: Terraform CI Pipeline

on:
    workflow_dispatch:
    pull_request:
    push:
    
     branches:
      - feat/infrastructure

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - name: Run Terraform Format Check
        run: terraform fmt -check
      - name: Run TFLint
        uses: wata727/tflint-action@v2

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v13
      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Run Terratest
        run: go test -v ./test/

  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan