name: "Terraform test GH actions"

on:
  workflow_dispatch:
    paths:
      - 'terraform/**'  # Manually trigger the workflow for changes in the terraform directory

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CREDS_VAR: ${{ secrets.CREDS_VAR }}  # Your combined credentials secret

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform  # Ensure this points to your Terraform config directory

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          
      - name: Terraform format
        id: fmt
        run: terraform fmt

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Set environment variables from CREDS_VAR
        id: set-creds
        run: |
          IFS='|' read -r CLOUD_FLARE_API_TOKEN CLOUD_FLARE_ZONE_ID NEW_RELIC_LICENSE_KEY <<< "${{ env.CREDS_VAR }}"
          echo "cloudflare_api_token=${CLOUD_FLARE_API_TOKEN}" >> $GITHUB_ENV
          echo "cloudflare_zone_id=${CLOUD_FLARE_ZONE_ID}" >> $GITHUB_ENV
          echo "new_relic_license_key=${NEW_RELIC_LICENSE_KEY}" >> $GITHUB_ENV

      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve \
          -var="cloudflare_api_token=${{ env.cloudflare_api_token }}" \
          -var="cloudflare_zone_id=${{ env.cloudflare_zone_id }}" \
          -var="new_relic_license_key=${{ env.new_relic_license_key }}"

      - name: Terraform destroy
        id: destroy
        run: terraform destroy --auto-approve \
          -var="cloudflare_api_token=${{ env.cloudflare_api_token }}" \
          -var="cloudflare_zone_id=${{ env.cloudflare_zone_id }}" \
          -var="new_relic_license_key=${{ env.new_relic_license_key }}"
