name: MY NEw PIPELINE

on:
  workflow_dispatch:
  push:
      branches:
        - feat/infrastructure

permissions: write-all

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_API_KEY }}
          
                # Set Docker image tag (using the Git SHA or another strategy)
      - name: Set Docker image tag
        id: docker_tag
        run: |
         IMAGE_TAG="${GITHUB_SHA::7}"
         echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t zinx666/mediaverse:latest .
        
      - name: Push Docker Image
        run: docker push zinx666/mediaverse:latest

  apply:
    name: Terraform Apply 
    uses: ./.github/workflows/terraform-apply.yml
    needs: [build_and_push]
    secrets: inherit   

  destroy:
    name: Terraform Destroy
    uses: ./.github/workflows/terraform-destroy.yml
    needs: [apply]
    secrets: inherit

