name: "Terraform test GH actions"

on:
  workflow_dispatch:
    paths:
      - 'terraform/**'  # Manually trigger the workflow for changes in the terraform directory

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CREDS_VAR: ${{ secrets.CREDS_VAR }}  # Change this to a valid environment variable name

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform  # Ensure this points to your Terraform config directory

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          
      - name: Terraform format
        id: fmt
        run: terraform fmt

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"

      - name: Terraform validate
        id: validate
        run: terraform validate
        
      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve -var="creds_var=${{ env.CREDS_VAR }}"  # Correctly reference the environment variable

      - name: Terraform destroy
        id: destroy
        run: terraform destroy --auto-approve -var="creds_var=${{ env.CREDS_VAR }}"  # Correctly reference the environment variable
