name: CI

on:
  push:
    branches:
      - dev  # Change this to your default branch if necessary
  pull_request:
    branches:
      - main  # Change this as necessary

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if your requirements file has a different name

      - name: Run tests
        run: |
          pytest tests/  # Adjust the path to your test directory if necessary
