name: Python Linting and Tests

on:
    push:
        branches:
          - feat/backend
    pull_request:
      branches:
        - main
      paths-ignore:
        - '**/*.md'

jobs:
  lint-and-test:
    name: 
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Step 4: Lint Python Code
      - name: Lint Python Code
        run: |
          python -m black .

  snyk-scan:

    name: Example workflow for Python using Snyk
    jobs:
      security:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/python@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}