name: Example workflow for Python using Snyk
on: 
  push:
    branches:
      - staging
      - dev
      - main
  pull_request:
    branches:
      - main
      - staging
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Requirements
        run: pip install -r requirements.txt
        working-directory: ./  # Specify the correct directory if needed
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}




