name: Example workflow for Python using Snyk
on: 
  push:
    branches:
      - feat/backend
  pull_request:
    branches:
      - dev
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Requirements
        run: pip install -r requirements.txt
        working-directory: 
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}