name: Python Linting, Tests, and Snyk Vulnerability Check

on:
  push:
    branches:
      - feat/backend  # Trigger on push to feat/backend
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  lint-and-test:
    name: Lint Python Code and Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Lint Python code with flake8 and black
      - name: Lint with black
        run: |
          black .

  snyk-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@v2
        continue-on-error: true  # Allow errors to continue so SARIF can be uploaded
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      # Step 3: Upload results to GitHub Code Scanning
      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
