name: Snyk Terraform IaC Security

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - staging

jobs:
  snyk-iac-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: List files (for debugging)
        run: ls -l

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk IaC scan (Terraform)
        run: snyk iac test terraform/ --sarif-file-output=snyk-terraform.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-terraform.sarif
