name: SNYK SCANNING
on:
  push:
    branches: 
      - feat/infrastructure
      - staging
      - main
  workflow_dispatch:
  pull_request:
    branches: 
      - staging
      - main
permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Step to format Terraform files
      - name: Run terraform fmt to check formatting
        run: terraform fmt -check -recursive
        working-directory: terraform

      # Step to validate Terraform files
      - name: Run terraform validate to check syntax
        run: terraform validate
        working-directory: terraform

      # Snyk scan step
      - name: Run Snyk to check all Terraform configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          path: terraform/

      # Upload SARIF results to GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
