name: Snyk Security Scans

on:
  pull_request:
    branches:
      - rc/*
  push:
    branches:
      - main
      - rc/*

permissions:
  contents: read
  security-events: write

jobs:
  snyk-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # --- Dependency Scanning ---
      - name: Snyk Dependency Test (PR)
        if: github.event_name == 'pull_request'
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --report
            --sarif-file-output=snyk-deps.sarif
            --project-name=actions-generator-ci:deps

      - name: Upload Snyk Dependency SARIF
        if: github.event_name == 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-deps.sarif

      - name: Snyk Dependency Monitor (main/rc)
        if: github.event_name == 'push'
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --project-name=actions-generator-ci:deps

      # --- IaC Scanning ---
      - name: Snyk IaC Test (PR)
        if: github.event_name == 'pull_request'
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --report
            --sarif-file-output=snyk-iac.sarif
            --project-name=actions-generator-ci:iac

      - name: Upload Snyk IaC SARIF
        if: github.event_name == 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-iac.sarif

      - name: Snyk IaC Monitor (main/rc)
        if: github.event_name == 'push'
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --project-name=actions-generator-ci:iac
