name: Snyk Security latest from marketplace

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # --- Snyk Code analysis ---
      - name: Snyk Code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk code test . \
            --report \
            --project-name=${{ github.base_ref }} \
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} \
            --target-reference=${{ github.base_ref }}

      # --- Snyk Open Source (Python deps) ---
      - name: Snyk Open Source monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk monitor \
            --project-name=${{ github.base_ref }} \
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} \
            --target-reference=${{ github.base_ref }}

      # --- Snyk IaC (Infrastructure as Code) ---
      - name: Snyk IaC test and report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk iac test . \
            --report \
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} \
            --target-reference=${{ github.base_ref }} || true
