name: Snyk Security Scans (RC Branch PRs)

concurrency:
  group: snyk-security-${{ github.event.number || github.run_id }}
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - rc/*

permissions:
  contents: read
  security-events: write

jobs:
  snyk-scans:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scan-type: [dependency, iac, sast]
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # === Dependency Scan ===
      - name: Snyk Dependency Scan
        if: matrix.scan-type == 'dependency'
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --severity-threshold=high
            --project-name=actions-generator-ci:deps-${{ github.base_ref }}
            --target-reference=${{ github.head_ref }}

      # === IaC Scan ===
      - name: Snyk IaC Scan
        if: matrix.scan-type == 'iac'
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --severity-threshold=high
            --project-name=actions-generator-ci:iac-${{ github.base_ref }}
            --target-reference=${{ github.head_ref }}

      # === SAST Scan ===
      - name: Snyk SAST Scan
        if: matrix.scan-type == 'sast'
        uses: snyk/actions/code@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --severity-threshold=high
            --project-name=actions-generator-ci:sast-${{ github.base_ref }}
            --target-reference=${{ github.head_ref }}
