name: Snyk Security latest from marketplace

on:
  pull_request:
    branches: ["rc/*"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test . --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} --project-name="MYAGREPO:releases" --target-reference=${{ github.base_ref }} --sarif > snyk-code.sarif || true --report

      - name: Snyk Code monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code monitor --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} --project-name="MYAGREPO:releases" --target-reference=${{ github.base_ref }} || true --report

      - name: Snyk Open Source monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --all-projects --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} --project-name="MYAGREPO:releases" --target-reference=${{ github.base_ref }} || true

      - name: Snyk IaC test and report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk iac test . --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} --project-name="MYAGREPO:releases" --target-reference=${{ github.base_ref }} --report || true

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
