name: Snyk Security Scans (RC Branch PRs)

concurrency:
  group: snyk-security-${{ github.event.number || github.run_id }}
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - rc/*

permissions:
  contents: read
  security-events: write

jobs:
  # Job 1: Dependency and SAST scans
  code-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk Dependency Scan (Python)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --file=requirements.txt \
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} \
            --target-reference=${{ github.head_ref }} \
            --project-name="actions-generator-ci:deps-${{ github.head_ref }}" \
            --sarif-file-output=dependency.sarif || true

      - name: Snyk SAST Scan (Code Security)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk code test \
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} \
            --target-reference=${{ github.head_ref }} \
            --project-name="actions-generator-ci:sast-${{ github.head_ref }}" \
            --sarif-file-output=sast.sarif || true

      - name: Upload Dependency SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: dependency.sarif

      - name: Upload SAST SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sast.sarif
