name: Snyk IaC Scan (Standalone)

on:
  pull_request:
    branches:
      - rc/*

permissions:
  contents: read
  security-events: write

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk IaC Test & Generate SARIF
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >
            . 
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --target-reference=${{ github.head_ref }}
            --project-name="iac-only-${{ github.head_ref }}"
            --sarif-file-output=iac.sarif


      - name: Upload IaC SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: iac.sarif
