name: Snyk Security Scans

on:
  pull_request:
    branches:
      - rc/*

permissions:
  contents: read
  security-events: write

jobs:
  snyk-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Snyk Dependency Test
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN}}
        with:
          command: test
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --severity-threshold=high

      - name: Snyk IaC Test
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN}}
        with:
          command: test
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --severity-threshold=high

      - name: Snyk Monitor to UI
        uses: snyk/actions/setup@master
        with:
          version: 'latest'
      - name: Monitor Projects to Snyk
        run: snyk monitor --all-projects \
          --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} \
          --target-reference=${{ github.head_ref }} \
          --project-name=actions-generator-ci
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_NOONEBLAIN }}
