name: Snyk test 8_6

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-iac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk IaC scan (Terraform)
        run: snyk iac test terraform/ --sarif-file-output=snyk-terraform.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: List workspace files for debugging
        run: ls -lh

      - name: Fix SARIF severity (if needed)
        run: |
          if grep -q '"security-severity": "undefined"' snyk-terraform.sarif; then
            sed -i 's/"security-severity": "undefined"/"security-severity": 5.0/g' snyk-terraform.sarif
          fi

      - name: Check SARIF file exists
        run: |
          if [ ! -f snyk-terraform.sarif ]; then
            echo "SARIF file not found! Exiting."
            exit 1
          fi

      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-terraform.sarif
