name: Snyk Combined Scans with SARIF Reporting

on:
  pull_request:
    branches:
      - rc/*

permissions:
  contents: read
  security-events: write

jobs:
  snyk-security-scans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Snyk Dependency Scan (Python) & Generate SARIF
        uses: snyk/actions/python@master
        id: python_scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --target-reference=${{ github.head_ref }}
            --severity-threshold=high
            --sarif-file-output=dependency.sarif

      - name: Upload Dependency SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: dependency.sarif

      - name: Snyk SAST Scan (Node example) & Generate SARIF
        uses: snyk/actions/node@master
        id: sast_scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --target-reference=${{ github.head_ref }}
            --severity-threshold=high
            --sarif-file-output=sast.sarif

      - name: Upload SAST SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: sast.sarif

      - name: Snyk IaC Scan & Generate SARIF
        uses: snyk/actions/iac@master
        id: iac_scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >
            --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }}
            --target-reference=${{ github.head_ref }}
            --severity-threshold=high
            --sarif-file-output=iac.sarif

      - name: Upload IaC SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: iac.sarif

