name: Snyk Security Scans
concurrency:
  group: snyk-security-${{ github.event.number || github.run_id }}
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - rc/*

permissions:
  contents: read
  security-events: write

jobs:
  snyk-scans:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scan-type: [dependency, sast, iac]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust to your Flask project's Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ... Your Snyk scan steps for each matrix entry ...

      - name: Monitor to Nooneblain Org
        run: snyk monitor --all-projects --org=${{ secrets.SNYK_ORG_ID_NOONEBLAIN }} --target-reference=${{ github.head_ref }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_NOONEBLAIN }}

      # - name: Monitor to My Second Org
      #   run: snyk monitor --all-projects --org=${{ secrets.SNYK_ORG_ID_SECONDORG }} --target-reference=${{ github.head_ref }}
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_SECONDORG }}
