name: Snyk Python Security Debug

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - staging

jobs:
  snyk-security:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Python Setup ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip list

      # --- Python Dependency Scan (Debug) ---
      - name: Debug Python dependency scan
        run: |
          echo "=== Dependency scan start: $(date) ==="
          snyk test --sarif-file-output=snyk-python-deps.sarif --file=requirements.txt --debug
          echo "=== Dependency scan end: $(date) ==="
          ls -lah
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload Python dependency SARIF to Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-python-deps.sarif

      # --- Python Code Scan (Debug) ---
      - name: Debug Python code scan
        run: |
          echo "=== Code scan start: $(date) ==="
          snyk code test --sarif-file-output=snyk-python-code.sarif --debug src/
          echo "=== Code scan end: $(date) ==="
          ls -lah
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload Python code SARIF to Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-python-code.sarif
