name: Snyk Python Security Minimal

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - staging

jobs:
  snyk-security:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files (for debugging)
        run: ls -l

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Snyk dependency scan
        run: snyk test --sarif-file-output=snyk-python-deps.sarif --file=requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-python-deps.sarif
