name: Snyk Python and Terraform Security Scanning

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - staging

jobs:
  security:
    permissions:
      contents: read
      security-events: write
      actions: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- PYTHON SCANNING ---

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Snyk dependency scan (creates SARIF)
      - name: Snyk Python dependency scan (SARIF)
        run: snyk test --all-projects --sarif-file-output=snyk-python.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Snyk code (static analysis) scan (creates SARIF)
      - name: Snyk Python code scan (SARIF)
        run: snyk code test --sarif-file-output=snyk-python-code.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Merge SARIF files (optional: if you want one Python SARIF report)
      - name: Merge SARIF reports (optional)
        run: |
          jq -s '.[0].runs += .[1].runs | .[0]' snyk-python.sarif snyk-python-code.sarif > snyk-python-merged.sarif

      - name: Upload Python SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-python-merged.sarif

      # --- TERRAFORM SCANNING ---

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      # Snyk IaC scan (creates SARIF)
      - name: Snyk Terraform IaC scan (SARIF)
        run: snyk iac test terraform/ --sarif-file-output=snyk-terraform.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Terraform SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-terraform.sarif
