name: Snyk IaC and Python Security Scanning

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - staging

jobs:
  snyk-security:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Terraform (IaC) Scan ---
      - name: Snyk IaC scan (SARIF)
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-terraform.sarif terraform/

      - name: Upload Terraform SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-terraform.sarif

      # --- Python Setup ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # --- Python Code Scan ---
      - name: Snyk Python code scan (SARIF)
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: code test --sarif-file-output=snyk-python-code.sarif

      - name: Upload Python code SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-python-code.sarif

      # --- Python Dependency Scan ---
      - name: Snyk Python dependency scan (SARIF)
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --sarif-file-output=snyk-python-deps.sarif

      - name: Upload Python dependency SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-python-deps.sarif
