name: Snyk Python Scanning and Terraform Security Scanning
on: 
  push:
    branches:
      dev
  pull_request:
    branches:
      - main
      - staging
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Requirements
        run: pip install -r requirements.txt
        working-directory: ./
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1  # Change this to your region

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/
      # Step to format Terraform files
      - name: Run terraform fmt to check formatting
        run: terraform fmt
        working-directory: terraform/
      # Step to validate Terraform files
      - name: Run terraform validate to check syntax
        run: terraform validate
        working-directory: terraform/
      # Snyk scan step
      - name: Run Snyk to check all Terraform configuration files for security issues
        continue-on-error: true
        
        uses: snyk/actions/iac@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        

