name: Terraform Destroy
on:
  workflow_dispatch:
  workflow_call:
env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
jobs:
  terraform_destroy:
    name: Destroy infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    
    steps:
    - name: populate secrets.auto.tfvars
      run: |
        cat <<EOF >> secrets.auto.tfvars
        cloudflare_api_token = "${{secrets.CLOUDFLARE_API_TOKEN}}"
        cloudflare_zone_id = "${{secrets.CLOUDFLARE_ZONE_ID}}"
        new_relic_license_key = "${{secrets.NEW_RELIC_LICENSE_KEY}}"
        EOF

    - uses: actions/checkout@v4
    - name: Terraform init and destroy
      run: terraform init && terraform destroy --auto-approve