name: Terraform Apply

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string

jobs:
  terraform-apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  # Adjust Terraform version as needed

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: |
          terraform destroy -auto-approve -var="image_tag=${{ inputs.IMAGE_TAG }}"
        env:
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}

      - name: Terraform Output
        run: terraform output
