name: MY DOCKER NEW RELIC TEST

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Create newrelic.ini from secret stored in GitHub Secrets
      - name: Create newrelic.ini
        run: echo "${{ secrets.NEW_RELIC_CONFIG2 }}" > newrelic.ini

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_API_KEY }}

      # Set Docker image tag using GitHub SHA
      - name: Set Docker Image Tag
        id: docker_tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/actions_generator:${{ env.IMAGE_TAG }} .

      # Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/actions_generator:${{ env.IMAGE_TAG }}
